### ISSUE TITLE
[Help Wanted] API (Job, processsmsconversations) does not exist

### ISSUE THREAD

**Issue by hamboneZA** [3sd/civicrm-sms-conversation#9]
Yo! Awesome tool, thanks! I'm having a spot of trouble implementing it though. This is the message on the Schedule SMS Conversations scheduled job when sending to multiple contacts found in groups.

`Parameters parsed (and passed to API method): 
a:1:{s:7:"version";i:3;}

Full message: 
Finished execution of Schedule SMS Conversations with result: Failure, Error message: API (Job, processsmsconversations) does not exist (join the API team and implement it!)`

Any ideas?

**Comment by michaelmcandrew** [comment]
Hi there!

Thanks for your issue report. That was a bug (you are an early adopter!).

Try replacing processsmsconversations with process_sms_conversations and it should work.

I have pushed a fix for this into master (https://github.com/3sd/civicrm-sms-conversation/commit/94c2b91eea525a3d7876ff91f584bf526a2ea16f) but I am not sure sure if upgrading to the fixed version will fix it automatically. Your best bet would be to replace the code with the latest version and then edit the scheduled job manually, or delete the already original one if it has already created a new one.

Happy to clarify anything if required.

**Comment by hamboneZA** [comment]
All good - I'll make the changes manually to the scheduled job and update smsconversation.mgd.php. Thanks for the speedy fix.

**Comment by michaelmcandrew** [comment]
no problem - have fun with it.
